In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
total = pd.read_csv('인총 주택 정보 데이터.csv')
total

,﻿STDYY,CSOPAR_CODE,ADSTRD_CODE,ATPT_NM,SIGNGU_NM,ADSTRD_NM,TOT_HOUSE_CO,MLPXHOU_CO,SLH_HOS,APT_CO,...,PD_3OVER_4BELO_HOUSE_CO,PD_4OVER_5BELO_HOUSE_CO,PD_5OVER_10BELO_HOUSE_CO,PD_10OVER_15BELO_HOUSE_CO,PD_15OVER_20BELO_HOUSE_CO,PD_20OVER_30BELO_HOUSE_CO,PD_30OVER_40BELO_HOUSE_CO,PD_40OVER_50BELO_HOUSE_CO,PD_50ABOVE_HOUSE_CO,NON_SMGU_HOUSE_CO
0,2015,1.101070e+12,1111051500,서울,종로구,청운효자동,128,19,81,0,...,19,0,0,18,13,13,0,5,48,0
1,2015,1.101070e+12,1111051500,서울,종로구,청운효자동,210,138,16,8,...,0,0,0,133,65,0,0,0,0,0
2,2015,1.101070e+12,1111051500,서울,종로구,청운효자동,143,35,104,0,...,0,0,8,26,13,16,5,20,54,0
3,2015,1.101070e+12,1111051500,서울,종로구,청운효자동,157,127,29,0,...,0,0,0,11,105,5,0,0,22,0
4,2015,1.101070e+12,1111051500,서울,종로구,청운효자동,127,97,6,0,...,0,0,0,27,93,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2015,1.101060e+12,1111060000,서울,종로구,가회동,119,0,98,0,...,0,0,0,0,30,7,0,10,62,0
146,2015,1.101060e+12,1111060000,서울,종로구,가회동,110,0,78,0,...,0,0,0,19,20,14,0,5,50,0
147,2015,1.101060e+12,1111060000,서울,종로구,가회동,200,49,150,0,...,0,0,6,0,46,21,0,12,106,0
148,2015,1.101060e+12,1111060000,서울,종로구,가회동,155,62,75,0,...,0,0,0,40,41,9,0,12,45,0
149,2015,1.101060e+12,1111060000,서울,종로구,가회동,211,200,10,0,...,0,0,5,5,192,0,0,0,5,0

In [3]:
total.columns = ['기준년','집계구코드','행정동코드','시도명','시군구명','행정동명',
                '총주택수','다세대주택수','단독주택수','아파트수','연립주택수','영업용건물내주택수','주택이외거처수',
                '면적20이하','면적20이상40이하','면적40이상60이하','면적60이상85이하','면적85이상100이하','면적100이상130이하','면적130이상165이하','면적165이상230이하','면적230초과',
                '기간1년미만','기간1년이상2년미만','기간2년이상3년미만','기간3년이상4년미만','기간4년이상5년미만','기간5년이상10년미만',
                 '기간10년이상15년미만','기간15년이상20년미만','기간20년이상30년미만','기간30년이상40년미만','기간40년이상50년미만','기간50년이상','자료없는집계구']
total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 35 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   기준년           150 non-null    int64
 1   집계구코드         150 non-null    float64
 2   행정동코드         150 non-null    int64
 3   시도명           150 non-null    object
 4   시군구명          150 non-null    object
 5   행정동명          150 non-null    object
 6   총주택수          150 non-null    int64
 7   다세대주택수        150 non-null    int64
 8   단독주택수         150 non-null    int64
 9   아파트수          150 non-null    int64
 10  연립주택수         150 non-null    int64
 11  영업용건물내주택수     150 non-null    int64
 12  주택이외거처수       150 non-null    int64
 13  면적20이하        150 non-null    int64
 14  면적20이상40이하    150 non-null    int64
 15  면적40이상60이하    150 non-null    int64
 16  면적60이상85이하    150 non-null    int64
 17  면적85이상100이하   150 non-null    int64
 18  면적100이상130이하  150 non-null    int64
 19  면적130이상165이하  150 non-null    int64
 20  면적165이상230이하  150 non-null    int64
 21  면적230초과       150 non-null    int64
 22  기간1년미만        150 non-null    int64
 23  기간1년이상2년미만    150 non-null    int64
 24  기간2년이상3년미만    150 non-null    int64
 25  기간3년이상4년미만    150 non-null    int64
 26  기간4년이상5년미만    150 non-null    int64
 27  기간5년이상10년미만   150 non-null    int64
 28  기간10년이상15년미만  150 non-null    int64
 29  기간15년이상20년미만  150 non-null    int64
 30  기간20년이상30년미만  150 non-null    int64
 31  기간30년이상40년미만  150 non-null    int64
 32  기간40년이상50년미만  150 non-null    int64
 33  기간50년이상       150 non-null    int64
 34  자료없는집계구       150 non-null    int64
dtypes: float64(1), int64(31), object(3)
memory usage: 41.1+ KB

In [4]:
# 특정 열 추출
total = total.iloc[:, [0,3,4,6,7,8,9,10,11,12]]
total

      기준년 시도명 시군구명  총주택수  다세대주택수  단독주택수  아파트수  연립주택수  영업용건물내주택수  주택이외거처수
0    2015  서울  종로구   128      19     81     0     19          9        9
1    2015  서울  종로구   210     138     16     8     48          0        0
2    2015  서울  종로구   143      35    104     0      0          0        0
3    2015  서울  종로구   157     127     29     0      0          0        0
4    2015  서울  종로구   127      97      6     0     24          0        0
..    ...  ..  ...   ...     ...    ...   ...    ...        ...      ...
145  2015  서울  종로구   119       0     98     0     14          5        8
146  2015  서울  종로구   110       0     78     0     23          5        6
147  2015  서울  종로구   200      49    150     0      0          0        0
148  2015  서울  종로구   155      62     75     0     17          0        0
149  2015  서울  종로구   211     200     10     0      0          0        0

[150 rows x 10 columns]

In [5]:
total['기준년'] = total['기준년'].astype(str)
total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   기준년        150 non-null    object
 1   시도명        150 non-null    object
 2   시군구명       150 non-null    object
 3   총주택수       150 non-null    int64
 4   다세대주택수     150 non-null    int64
 5   단독주택수      150 non-null    int64
 6   아파트수       150 non-null    int64
 7   연립주택수      150 non-null    int64
 8   영업용건물내주택수  150 non-null    int64
 9   주택이외거처수    150 non-null    int64
dtypes: int64(7), object(3)
memory usage: 11.8+ KB

C:\Users\ch980\AppData\Local\Temp/ipykernel_8716/322574177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total['기준년'] = total['기준년'].astype(str)

In [6]:
total15 = total[total['기준년'] == '2015']
total16 = total[total['기준년'] == '2016']
total17 = total[total['기준년'] == '2017']

In [7]:
total15

      기준년 시도명 시군구명  총주택수  다세대주택수  단독주택수  아파트수  연립주택수  영업용건물내주택수  주택이외거처수
0    2015  서울  종로구   128      19     81     0     19          9        9
1    2015  서울  종로구   210     138     16     8     48          0        0
2    2015  서울  종로구   143      35    104     0      0          0        0
3    2015  서울  종로구   157     127     29     0      0          0        0
4    2015  서울  종로구   127      97      6     0     24          0        0
..    ...  ..  ...   ...     ...    ...   ...    ...        ...      ...
145  2015  서울  종로구   119       0     98     0     14          5        8
146  2015  서울  종로구   110       0     78     0     23          5        6
147  2015  서울  종로구   200      49    150     0      0          0        0
148  2015  서울  종로구   155      62     75     0     17          0        0
149  2015  서울  종로구   211     200     10     0      0          0        0

[150 rows x 10 columns]